### ISSUE TITLE
Fails with PSRJ

### ISSUE THREAD

**Issue by paulray** [jcolen/qtiPINT#1]
Right now it looks for the "PSR" parameter in the par file for something.  This should allow "PSRJ" as a synonym.

**Comment by jcolen** [comment]
Can you post the parfile you used to get this bug? I cannot reproduce it by changing PSR to PSRJ. PINT timing models allow PSRJ and PSRB as aliases for PSR and any lines named PSRJ are translated to the PSR parameter, it looks like

**Comment by paulray** [comment]
Oops, I think I was misunderstanding the error.  I got this error:
```
WARNING: No pulse numbers for TOAs [pint.toa]
WARNING:astropy:No pulse numbers for TOAs
ERROR: No pulse numbers with TOAs using TRACK -2 [pint.residuals]
ERROR:astropy:No pulse numbers with TOAs using TRACK -2
Traceback (most recent call last):
  File "/Users/paulr/Library/Python/2.7/bin/qtip", line 11, in <module>
    load_entry_point('qtiPINT', 'console_scripts', 'qtip')()
  File "/Users/paulr/src/qtiPINT/qtipint/qtip.py", line 514, in main
    qtipwin = QtipWindow(parfile=options.parfile, timfile=options.timfile)
  File "/Users/paulr/src/qtiPINT/qtipint/qtip.py", line 104, in __init__
    timfilename=timfile)
  File "/Users/paulr/src/qtiPINT/qtipint/qtip.py", line 382, in requestOpenPlk
    self.openPlkPulsar(parfilename, timfilename, testpulsar=testpulsar)
  File "/Users/paulr/src/qtiPINT/qtipint/qtip.py", line 436, in openPlkPulsar
    psr = self.kernel.shell.ns_table['user_local']['psr']
KeyError: 'psr'
```
But, I think the real error was the TRACK -2 thing.  Sorry for the confusion!
It would be good it TRACK -2 didn't fail if the tim file didn't have pulse numbers, but was just ignored with a warning.
