### ISSUE TITLE
get rid of jdcal requirement and use astropy

### ISSUE THREAD

**Issue by scottransom** [jcolen/qtiPINT#9]
'nuff said.

**Comment by scottransom** [comment]
I know you closed it, but a similar argument could probably be made for replacing pyephem with astropy....  (and I'm curious why h5py is required as well...)

**Comment by jcolen** [comment]
Because of these dependencies, I'm working on a Tkinter based version of this entire system to be added to the main PINT repository. It's currently runnable as the pintkinter script in my PINT fork, and will be submitted as a pull request once I add enough features.

**Comment by scottransom** [comment]
That sounds awesome.  I will try to test it this weekend.
